<h1>Numpy</h1>
<ol type="1">
    <li>pip install numpy</li>
    <li>import numpy as np</li>
    <li>Open the file in terminal</li>
    <li>python -m notebook</li>
</ol>


<h1>Type-1<br></h1>

In [1]:
import numpy as np
n = [1,2,3,4,5]
n[0:3]

[1, 2, 3]

In [5]:
import numpy as np
m = [1,2,3,4,5,6,7,8,9]
m[0:7]

[1, 2, 3, 4, 5, 6, 7]

<h1>Type-2<br></h1>

In [6]:
m[-1]

9

In [7]:
m[-2]

8

In [8]:
m[-3:-1]

[7, 8]

Now work Right to Left

In [9]:
m[-1:-3]

[]

<h1>Type-3<br></h1>

In [11]:
a=np.array([6,7,8,9])
a[0:2]

array([6, 7])

In [12]:
a[1:3]

array([7, 8])

In [13]:
b=np.array([[1,2,3],
            [4,5,6],
            [8,9,10]])

In [14]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [15]:
b[1,2]

6

In [16]:
b[0:2,2]

array([3, 6])

In [17]:
b[0:3,2]

array([ 3,  6, 10])

In [14]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [19]:
b[1,0:2]

array([4, 5])

In [16]:
for row in b :
    print(row)

[1 2 3]
[4 5 6]
[ 8  9 10]


In [18]:
for cell in b.flat:
    print(cell)

1
2
3
4
5
6
8
9
10


<h1>Type-4</h1>

In [13]:
import numpy as np
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)

In [21]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [22]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [23]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [24]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

<h1>Type-5</h1>

<h5>For cutting array horizontal <br></h5>

In [15]:
a=np.arange(30).reshape(2,15)

In [27]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [28]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

<h5>To get all result indivisibly<br></h5>

In [30]:
result = np.hsplit(a,3)

In [31]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [32]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [33]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

<h5>For cutting array vertically <br></h5>

In [34]:
result = np.vsplit(a,2)

In [35]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [36]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

<h1>Type-6<br></h1>

In [3]:
import numpy as np
a = np.arange(12).reshape(3,4)

In [4]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
b = a > 4

In [6]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

<h5>For true value print the number from array</h5>

In [7]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

For replace b=a>4 into -1

In [8]:
a[b]=-1

In [9]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])