<h1>Class 2</h1>

<h3>Type-1</h3>

<h5>One dimensional array</h5>

In [1]:
import numpy as np
a = np.array([5,6,7])

In [2]:
a[0]

5

In [3]:
a[1]

6

In [5]:
a[2]

7

<h5>Two dimensional array</h5>

In [6]:
a = np.array([[1,2],[3,4],[5,6]])

In [7]:
a.ndim

2

In [8]:
a.itemsize

4

In [9]:
a.dtype

dtype('int32')

Different data type

In [12]:
a = np.array([[1,2],[3,4],[5,6]], dtype = np.float64)

In [13]:
a.itemsize

8

In [14]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [1]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]], dtype = complex)

In [2]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
l = range(5)

In [6]:
l

range(0, 5)

In [7]:
l[0]

0

In [8]:
l[1]

1

In [9]:
np.arange(1,5)

array([1, 2, 3, 4])

In [10]:
np.arange(1,5,2)

array([1, 3])

In [11]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [13]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [14]:
a = np.array([[1,2],[3,4],[5,6]])

In [15]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
a.shape

(3, 2)

In [17]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [19]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [20]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])