<h1 align="center">Numpy</h1>

<h3>Class-1</h3>

<ol type="1">
    <li>pip install numpy</li>
    <li>import numpy as np</li>
    <li>Open the file in terminal</li>
    <li>python -m notebook</li>
</ol>

<h4>Type-1</h4>

In [2]:
import numpy as np
a = np.array([1,2,3])


In [3]:
a

array([1, 2, 3])

In [4]:
a[0]

1

In [5]:
a[1]

2

In [6]:
a[2]

3

<h3>3 main benefits of numpy array over a python list</h3>
<ol type="1">
    <li>Less Memory</li>
    <li>Fast</li>
    <li>Convinien</li>
</ol>

Less Memory Proof


In [13]:
import numpy as np
import time
import sys
l = range(1000)
print(sys.getsizeof(5)*len(l))

array = np.arange(1000)
print(array.size*array.itemsize)

28000
4000


Fast

In [14]:
SIZE = 100000

l1 = range(SIZE)
l2 = range(SIZE)

start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print(" python list took :", (time.time()-start)*1000)

 python list took : 31.65602684020996


In [15]:
a1 = np.array(SIZE)
a2 = np.array(SIZE)
start = time.time()
result = a1 + a2
print("numpy took: ", (time.time()-start)*1000)

numpy took:  0.0


Convinien

In [16]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])


In [17]:
a1+a2

array([5, 7, 9])

In [19]:
a2-a1

array([3, 3, 3])

In [18]:
a1*a2

array([ 4, 10, 18])

In [20]:
a1/a2

array([0.25, 0.4 , 0.5 ])

<h1 align="center">Summary</h1>

<h3>Libary used</h3>
<h4>Numpy</h4>
<ol type="1">
    <li>a = np.array([1,2,3])  array for input</li>
    <li>a,a[0] to get array</li>
    <li>a = np.arange(1000)-- Without input we get array</li>
    <li>array addition,substrutaion,multipication,division</li>
</ol>

<h4>import time</h4>
<ol type="1">
    <li>start = time.time()</li>
    <li>(time.time() - start)*1000</li>
</ol>

<h4>import sys</h4>
<ol type="1">
    <li>sys.getsizeof(5)*len(l)</li>
</ol>